#############################################################################
# Makefile for building: qt5stuff
# Generated by qmake (2.01a) (Qt 5.0.0) on: Tue Apr 3 00:17:54 2012
# Project:  qt5stuff.pro
# Template: app
# Command: /home/george/Software/qt5/qtbase/bin/qmake CONFIG+=debug_and_release -o Makefile qt5stuff.pro
#############################################################################

first: debug
install: debug-install
uninstall: debug-uninstall
MAKEFILE      = Makefile
QMAKE         = /home/george/Software/qt5/qtbase/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		debug \
		release


debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: qt5stuff.pro  ../../../Software/qt5/qtbase/mkspecs/linux-g++-64/qmake.conf ../../../Software/qt5/qtbase/mkspecs/common/unix.conf \
		../../../Software/qt5/qtbase/mkspecs/common/linux.conf \
		../../../Software/qt5/qtbase/mkspecs/common/gcc-base.conf \
		../../../Software/qt5/qtbase/mkspecs/common/gcc-base-unix.conf \
		../../../Software/qt5/qtbase/mkspecs/common/g++-base.conf \
		../../../Software/qt5/qtbase/mkspecs/common/g++-unix.conf \
		../../../Software/qt5/qtbase/mkspecs/qconfig.pri \
		../../../Software/qt5/qtactiveqt/modules/qt_activeqt.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_activeqt.pri \
		../../../Software/qt5/qtconnectivity/modules/qt_bluetooth.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_bluetooth.pri \
		../../../Software/qt5/qttools/modules/qt_clucene.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_clucene.pri \
		../../../Software/qt5/qtbase/src/modules/qt_concurrent.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_concurrent.pri \
		../../../Software/qt5/qtpim/modules/qt_contacts.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_contacts.pri \
		../../../Software/qt5/qtbase/src/modules/qt_core.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_core.pri \
		../../../Software/qt5/qtbase/src/modules/qt_dbus.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_dbus.pri \
		../../../Software/qt5/qtdeclarative/modules/qt_declarative.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_declarative.pri \
		../../../Software/qt5/qttools/modules/qt_designer.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_designer.pri \
		../../../Software/qt5/qttools/modules/qt_designercomponents.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_designercomponents.pri \
		../../../Software/qt5/qtdoc/modules/qt_doc.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_doc.pri \
		../../../Software/qt5/qtfeedback/modules/qt_feedback.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_feedback.pri \
		../../../Software/qt5/qtdocgallery/modules/qt_gallery.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_gallery.pri \
		../../../Software/qt5/qtbase/src/modules/qt_gui.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_gui.pri \
		../../../Software/qt5/qttools/modules/qt_help.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_help.pri \
		../../../Software/qt5/qtjsondb/modules/qt_jsondb.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_jsondb.pri \
		../../../Software/qt5/qtjsondb/modules/qt_jsondbcompat.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_jsondbcompat.pri \
		../../../Software/qt5/qtlocation/modules/qt_location.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_location.pri \
		../../../Software/qt5/qtmultimedia/modules/qt_multimedia.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_multimedia.pri \
		../../../Software/qt5/qtmultimedia/modules/qt_multimediawidgets.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_multimediawidgets.pri \
		../../../Software/qt5/qtbase/src/modules/qt_network.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_network.pri \
		../../../Software/qt5/qtbase/src/modules/qt_opengl.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_opengl.pri \
		../../../Software/qt5/qtpim/modules/qt_organizer.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_organizer.pri \
		../../../Software/qt5/qtphonon/modules/qt_phonon.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_phonon.pri \
		../../../Software/qt5/qtbase/src/modules/qt_platformsupport.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_platformsupport.pri \
		../../../Software/qt5/qtbase/src/modules/qt_printsupport.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_printsupport.pri \
		../../../Software/qt5/qtsystems/modules/qt_publishsubscribe.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_publishsubscribe.pri \
		../../../Software/qt5/qtdeclarative/modules/qt_qml.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_qml.pri \
		../../../Software/qt5/qtdeclarative/modules/qt_qmldevtools.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_qmldevtools.pri \
		../../../Software/qt5/qtdeclarative/modules/qt_qmltest.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_qmltest.pri \
		../../../Software/qt5/qt3d/modules/qt_qt3d.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_qt3d.pri \
		../../../Software/qt5/qt3d/modules/qt_qt3dquick.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_qt3dquick.pri \
		../../../Software/qt5/qtdeclarative/modules/qt_quick.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_quick.pri \
		../../../Software/qt5/qtquick1/modules/qt_quick1.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_quick1.pri \
		../../../Software/qt5/qtscript/modules/qt_script.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_script.pri \
		../../../Software/qt5/qtscript/modules/qt_scripttools.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_scripttools.pri \
		../../../Software/qt5/qtsensors/modules/qt_sensors.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_sensors.pri \
		../../../Software/qt5/qtsystems/modules/qt_serviceframework.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_serviceframework.pri \
		../../../Software/qt5/qtbase/src/modules/qt_sql.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_sql.pri \
		../../../Software/qt5/qtsvg/modules/qt_svg.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_svg.pri \
		../../../Software/qt5/qtsystems/modules/qt_systeminfo.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_systeminfo.pri \
		../../../Software/qt5/qtbase/src/modules/qt_testlib.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_testlib.pri \
		../../../Software/qt5/qttools/modules/qt_uitools.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_uitools.pri \
		../../../Software/qt5/qtjsbackend/src/modules/qt_v8.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_v8.pri \
		../../../Software/qt5/qtpim/modules/qt_versit.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_versit.pri \
		../../../Software/qt5/qtpim/modules/qt_versitorganizer.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_versitorganizer.pri \
		../../../Software/qt5/qtwebkit/Tools/qmake/qt_webkit.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_webkit.pri \
		../../../Software/qt5/qtbase/src/modules/qt_widgets.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_widgets.pri \
		../../../Software/qt5/qtbase/src/modules/qt_xml.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_xml.pri \
		../../../Software/qt5/qtxmlpatterns/modules/qt_xmlpatterns.pri \
		../../../Software/qt5/qtbase/mkspecs/modules/qt_xmlpatterns.pri \
		../../../Software/qt5/qtbase/mkspecs/features/qt_functions.prf \
		../../../Software/qt5/qtbase/mkspecs/features/qt_config.prf \
		../../../Software/qt5/qtbase/mkspecs/features/exclusive_builds.prf \
		../../../Software/qt5/qtbase/mkspecs/features/default_pre.prf \
		../../../Software/qt5/qtbase/mkspecs/features/unix/default_pre.prf \
		../../../Software/qt5/qtbase/mkspecs/features/debug.prf \
		../../../Software/qt5/qtbase/mkspecs/features/debug_and_release.prf \
		../../../Software/qt5/qtbase/mkspecs/features/default_post.prf \
		../../../Software/qt5/qtbase/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Software/qt5/qtbase/mkspecs/features/warn_on.prf \
		../../../Software/qt5/qtbase/mkspecs/features/qt.prf \
		../../../Software/qt5/qtbase/mkspecs/features/unix/opengl.prf \
		../../../Software/qt5/qtbase/mkspecs/features/unix/thread.prf \
		../../../Software/qt5/qtbase/mkspecs/features/moc.prf \
		../../../Software/qt5/qtbase/mkspecs/features/wayland-scanner.prf \
		../../../Software/qt5/qtbase/mkspecs/features/resources.prf \
		../../../Software/qt5/qtbase/mkspecs/features/uic.prf \
		../../../Software/qt5/qtbase/mkspecs/features/yacc.prf \
		../../../Software/qt5/qtbase/mkspecs/features/lex.prf \
		../../../Software/qt5/qtbase/mkspecs/features/include_source_dir.prf \
		/home/george/Software/qt5/qtbase/lib/libQtWidgets.prl \
		/home/george/Software/qt5/qtbase/lib/libQtGui.prl \
		/home/george/Software/qt5/qtbase/lib/libQtCore.prl \
		/home/george/Software/qt5/qtbase/lib/libQtNetwork.prl
	$(QMAKE) CONFIG+=debug_and_release -o Makefile qt5stuff.pro
../../../Software/qt5/qtbase/mkspecs/common/unix.conf:
../../../Software/qt5/qtbase/mkspecs/common/linux.conf:
../../../Software/qt5/qtbase/mkspecs/common/gcc-base.conf:
../../../Software/qt5/qtbase/mkspecs/common/gcc-base-unix.conf:
../../../Software/qt5/qtbase/mkspecs/common/g++-base.conf:
../../../Software/qt5/qtbase/mkspecs/common/g++-unix.conf:
../../../Software/qt5/qtbase/mkspecs/qconfig.pri:
../../../Software/qt5/qtactiveqt/modules/qt_activeqt.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_activeqt.pri:
../../../Software/qt5/qtconnectivity/modules/qt_bluetooth.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_bluetooth.pri:
../../../Software/qt5/qttools/modules/qt_clucene.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_clucene.pri:
../../../Software/qt5/qtbase/src/modules/qt_concurrent.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_concurrent.pri:
../../../Software/qt5/qtpim/modules/qt_contacts.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_contacts.pri:
../../../Software/qt5/qtbase/src/modules/qt_core.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_core.pri:
../../../Software/qt5/qtbase/src/modules/qt_dbus.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_dbus.pri:
../../../Software/qt5/qtdeclarative/modules/qt_declarative.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_declarative.pri:
../../../Software/qt5/qttools/modules/qt_designer.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_designer.pri:
../../../Software/qt5/qttools/modules/qt_designercomponents.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_designercomponents.pri:
../../../Software/qt5/qtdoc/modules/qt_doc.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_doc.pri:
../../../Software/qt5/qtfeedback/modules/qt_feedback.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_feedback.pri:
../../../Software/qt5/qtdocgallery/modules/qt_gallery.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_gallery.pri:
../../../Software/qt5/qtbase/src/modules/qt_gui.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_gui.pri:
../../../Software/qt5/qttools/modules/qt_help.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_help.pri:
../../../Software/qt5/qtjsondb/modules/qt_jsondb.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_jsondb.pri:
../../../Software/qt5/qtjsondb/modules/qt_jsondbcompat.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_jsondbcompat.pri:
../../../Software/qt5/qtlocation/modules/qt_location.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_location.pri:
../../../Software/qt5/qtmultimedia/modules/qt_multimedia.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_multimedia.pri:
../../../Software/qt5/qtmultimedia/modules/qt_multimediawidgets.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_multimediawidgets.pri:
../../../Software/qt5/qtbase/src/modules/qt_network.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_network.pri:
../../../Software/qt5/qtbase/src/modules/qt_opengl.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_opengl.pri:
../../../Software/qt5/qtpim/modules/qt_organizer.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_organizer.pri:
../../../Software/qt5/qtphonon/modules/qt_phonon.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_phonon.pri:
../../../Software/qt5/qtbase/src/modules/qt_platformsupport.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_platformsupport.pri:
../../../Software/qt5/qtbase/src/modules/qt_printsupport.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_printsupport.pri:
../../../Software/qt5/qtsystems/modules/qt_publishsubscribe.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_publishsubscribe.pri:
../../../Software/qt5/qtdeclarative/modules/qt_qml.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_qml.pri:
../../../Software/qt5/qtdeclarative/modules/qt_qmldevtools.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_qmldevtools.pri:
../../../Software/qt5/qtdeclarative/modules/qt_qmltest.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_qmltest.pri:
../../../Software/qt5/qt3d/modules/qt_qt3d.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_qt3d.pri:
../../../Software/qt5/qt3d/modules/qt_qt3dquick.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_qt3dquick.pri:
../../../Software/qt5/qtdeclarative/modules/qt_quick.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_quick.pri:
../../../Software/qt5/qtquick1/modules/qt_quick1.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_quick1.pri:
../../../Software/qt5/qtscript/modules/qt_script.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_script.pri:
../../../Software/qt5/qtscript/modules/qt_scripttools.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_scripttools.pri:
../../../Software/qt5/qtsensors/modules/qt_sensors.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_sensors.pri:
../../../Software/qt5/qtsystems/modules/qt_serviceframework.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_serviceframework.pri:
../../../Software/qt5/qtbase/src/modules/qt_sql.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_sql.pri:
../../../Software/qt5/qtsvg/modules/qt_svg.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_svg.pri:
../../../Software/qt5/qtsystems/modules/qt_systeminfo.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_systeminfo.pri:
../../../Software/qt5/qtbase/src/modules/qt_testlib.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_testlib.pri:
../../../Software/qt5/qttools/modules/qt_uitools.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_uitools.pri:
../../../Software/qt5/qtjsbackend/src/modules/qt_v8.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_v8.pri:
../../../Software/qt5/qtpim/modules/qt_versit.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_versit.pri:
../../../Software/qt5/qtpim/modules/qt_versitorganizer.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_versitorganizer.pri:
../../../Software/qt5/qtwebkit/Tools/qmake/qt_webkit.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_webkit.pri:
../../../Software/qt5/qtbase/src/modules/qt_widgets.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_widgets.pri:
../../../Software/qt5/qtbase/src/modules/qt_xml.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_xml.pri:
../../../Software/qt5/qtxmlpatterns/modules/qt_xmlpatterns.pri:
../../../Software/qt5/qtbase/mkspecs/modules/qt_xmlpatterns.pri:
../../../Software/qt5/qtbase/mkspecs/features/qt_functions.prf:
../../../Software/qt5/qtbase/mkspecs/features/qt_config.prf:
../../../Software/qt5/qtbase/mkspecs/features/exclusive_builds.prf:
../../../Software/qt5/qtbase/mkspecs/features/default_pre.prf:
../../../Software/qt5/qtbase/mkspecs/features/unix/default_pre.prf:
../../../Software/qt5/qtbase/mkspecs/features/debug.prf:
../../../Software/qt5/qtbase/mkspecs/features/debug_and_release.prf:
../../../Software/qt5/qtbase/mkspecs/features/default_post.prf:
../../../Software/qt5/qtbase/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../Software/qt5/qtbase/mkspecs/features/warn_on.prf:
../../../Software/qt5/qtbase/mkspecs/features/qt.prf:
../../../Software/qt5/qtbase/mkspecs/features/unix/opengl.prf:
../../../Software/qt5/qtbase/mkspecs/features/unix/thread.prf:
../../../Software/qt5/qtbase/mkspecs/features/moc.prf:
../../../Software/qt5/qtbase/mkspecs/features/wayland-scanner.prf:
../../../Software/qt5/qtbase/mkspecs/features/resources.prf:
../../../Software/qt5/qtbase/mkspecs/features/uic.prf:
../../../Software/qt5/qtbase/mkspecs/features/yacc.prf:
../../../Software/qt5/qtbase/mkspecs/features/lex.prf:
../../../Software/qt5/qtbase/mkspecs/features/include_source_dir.prf:
/home/george/Software/qt5/qtbase/lib/libQtWidgets.prl:
/home/george/Software/qt5/qtbase/lib/libQtGui.prl:
/home/george/Software/qt5/qtbase/lib/libQtCore.prl:
/home/george/Software/qt5/qtbase/lib/libQtNetwork.prl:
qmake: qmake_all FORCE
	@$(QMAKE) CONFIG+=debug_and_release -o Makefile qt5stuff.pro

qmake_all: FORCE

make_default: debug-make_default release-make_default FORCE
make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile

check: first

debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
